# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 07:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='case_info',
            fields=[
                ('case_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=50)),
                ('e_mail', models.EmailField(max_length=254)),
                ('type', models.SmallIntegerField()),
                ('keyword', models.CharField(max_length=100)),
                ('count', models.IntegerField(default=0)),
                ('fromwhere', models.SmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='filter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.SmallIntegerField()),
                ('keyword', models.CharField(max_length=100)),
                ('filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smzdm.case_info')),
            ],
        ),
        migrations.CreateModel(
            name='his',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_id', models.CharField(max_length=50)),
                ('timesort', models.BigIntegerField()),
                ('user_email', models.EmailField(max_length=254)),
                ('inserted_timesort', models.CharField(default=0, max_length=50)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smzdm.case_info')),
            ],
        ),
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_id', models.CharField(blank=True, default=0, max_length=50)),
                ('article_title', models.CharField(blank=True, default=0, max_length=300)),
                ('brand', models.CharField(blank=True, default=0, max_length=50)),
                ('rmb_price', models.CharField(blank=True, default=0, max_length=50)),
                ('article_price', models.CharField(blank=True, default=0, max_length=200)),
                ('article_mall', models.CharField(blank=True, default=0, max_length=50)),
                ('article_content', models.CharField(blank=True, default=0, max_length=1000)),
                ('article_comment', models.IntegerField(blank=True, default=0)),
                ('article_collection', models.IntegerField(blank=True, default=0)),
                ('worthy_percentage', models.IntegerField(blank=True, default=0)),
                ('article_worthy', models.IntegerField(blank=True, default=0)),
                ('article_unworthy', models.IntegerField(blank=True, default=0)),
                ('article_rating', models.IntegerField(blank=True, default=0)),
                ('price_dimension', models.CharField(blank=True, default=0, max_length=50)),
                ('channel_dimension', models.CharField(blank=True, default=0, max_length=50)),
                ('cates_str', models.CharField(blank=True, default=0, max_length=100)),
                ('timesort', models.BigIntegerField(blank=True, default=0)),
                ('article_url', models.CharField(blank=True, default=0, max_length=200)),
                ('article_pic', models.CharField(blank=True, default=0, max_length=200)),
                ('article_link', models.CharField(blank=True, default=0, max_length=200)),
                ('article_data', models.CharField(blank=True, default=0, max_length=100)),
                ('article_download_pic', models.CharField(blank=True, default=0, max_length=100)),
            ],
        ),
    ]
