# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 03:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smzdm', '0002_auto_20160823_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='article_id',
            field=models.CharField(blank=True, default=0, max_length=50),
        ),
    ]
